#!/bin/bash
set -oue pipefail

logger "HorizonOS system post install"

systemctl enable horizon-update.timer

/usr/libexec/horizon-configure-flatpak
/usr/libexec/horizon-configure-sddm

logger "HorizonOS system post install complete"