#!/bin/bash
set -ouex pipefail

/usr/libexec/horizon-check-version $HOME/.horizon-version-actual
EXIT_CODE=$?

case $EXIT_CODE in
    0)
        ;;
    1)
        /usr/libexec/horizon-post-install-user
        /usr/libexec/horizon-post-update-user
        ;;
    2)
        /usr/libexec/horizon-post-update-user
        ;;
    10)
        exit 10
        ;;
    *)
        exit 99
        ;;
esac

\cp -f /etc/horizon-version $HOME/.horizon-version-actual
