#!/bin/bash
set -oue pipefail

logger "Starting HorizonOS system setup"

SERVICE="horizon-setup-user.service"
UNIT="/usr/lib/systemd/user/$SERVICE"

USER=$(awk -F: '$3 >= 1000 && $1 !~ /^systemd-/ {print $1; exit}' /etc/passwd)

if [ -z "$USER" ]; then
    echo "No user found"
    exit 1
fi

HOMEDIR=$(eval echo "~$USER")
WANTS="$HOMEDIR/.config/systemd/user/default.target.wants"

mkdir -p "$WANTS"

if [ ! -e "$WANTS/$SERVICE" ]; then
    ln -sf "$UNIT" "$WANTS/$SERVICE"
    chown -R "$USER:$USER" "$HOMEDIR/.config/systemd"
fi


if /usr/libexec/horizon-check-version /etc/horizon-version-actual; then
    exit 0
else
    EXIT_CODE=$?
fi

case $EXIT_CODE in
    1)
        /usr/libexec/horizon-post-install-system
        /usr/libexec/horizon-post-update-system
        ;;
    2)
        /usr/libexec/horizon-post-update-system
        ;;
    *)
        exit $EXIT_CODE
        ;;
esac

\cp -f /etc/horizon-version /etc/horizon-version-actual
exit 0
