#!/bin/bash
set -oue pipefail

logger "Configuring Plasma desktop settings for user"

plasma-apply-lookandfeel -a org.kde.breezetwilight.desktop
plasma-apply-colorscheme ClearSimple
plasma-apply-desktoptheme ClearSimple
plasma-apply-cursortheme breeze-cursors-light-plasma5

# Breeze
kwriteconfig6 --file breezerc --group "Common" --key "OutlineIntensity" "OutlineOff"
kwriteconfig6 --file breezerc --group "Windeco" --key "ButtonSize" "ButtonSmall"

# Icons
kwriteconfig6 --file kdeglobals --group "Icons" --key "Theme" "ElevenTwilight"

# KDE
kwriteconfig6 --file kdeglobals --group "KDE" --key "AnimationDurationFactor" 0.5

# KWin
kwriteconfig6 --file kwinrc --group "Plugins" --key "diminactiveEnabled" true

# Sound
kwriteconfig6 --file kdeglobals --group "Sounds" --key "Enable" false

# Fonts
kwriteconfig6 --file kdeglobals --group "General" --key "fixed" "Cascadia Mono,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
kwriteconfig6 --file kdeglobals --group "General" --key "font" "Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
kwriteconfig6 --file kdeglobals --group "General" --key "menuFont" "Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
kwriteconfig6 --file kdeglobals --group "General" --key "smallestReadableFont" "Adwaita Sans,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
kwriteconfig6 --file kdeglobals --group "General" --key "toolBarFont" "Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
kwriteconfig6 --file kdeglobals --group "WM" --key "activeFont" "Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

# Launch feedback
kwriteconfig6 --file klaunchrc --group "BusyCursorSettings" --key "Bouncing" false
kwriteconfig6 --file klaunchrc --group "FeedbackStyle" --key "BusyCursor" false

# PlasmaToolTips
kwriteconfig6 --file plasmarc --group "PlasmaToolTips" --key "Delay" -- -1

# Numpad
kwriteconfig6 --file kcminputrc --group "Keyboard" --key "NumLock" 0

# Splash
kwriteconfig6 --file ksplashrc --group "KSplash" --key "Theme" "colored-plasma-logo"

# Plasma shell
kwriteconfig6 --file plasmashellrc --group "PlasmaViews" --group "Panel 2" --key "floating" 0
kwriteconfig6 --file plasmashellrc --group "PlasmaViews" --group "Panel 2" --key "floatingApplets" 1
kwriteconfig6 --file plasmashellrc --group "PlasmaViews" --group "Panel 2" --key "panelOpacity" 1
kwriteconfig6 --file plasmashellrc --group "PlasmaViews" --group "Panel 2" --group "Defaults" --key "thickness" 32

# Session
kwriteconfig6 --file ksmserverrc --group "General" --key "confirmLogout" false
kwriteconfig6 --file ksmserverrc --group "General" --key "loginMode" "emptySession"

# Formats
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LANG" "en_US.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_ADDRESS" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_MEASUREMENT" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_MONETARY" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_NAME" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_NUMERIC" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_PAPER" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_TELEPHONE" "it_IT.UTF-8"
kwriteconfig6 --file plasma-localerc --group "Formats" --key "LC_TIME" "it_IT.UTF-8"
kwriteconfig6 --file kdeglobals --group "Locale" --key "BinaryUnitDialect" 1

# Discover updates
kwriteconfig6 --file PlasmaDiscoverUpdates --group "Global" --key "RequiredNotificationInterval" -- -1
kwriteconfig6 --file PlasmaDiscoverUpdates --group "Global" --key "UseUnattendedUpdates" false

# Dolphin
kwriteconfig6 --file dolphinrc --group "General" --key "ShowFullPath" true
kwriteconfig6 --file dolphinrc --group "General" --key "ShowStatusBar" "FullWidth"
kwriteconfig6 --file dolphinrc --group "DetailsMode" --key "PreviewSize" 22

# Wallpaper
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc --group "Containments" --group "1" --key "wallpaperplugin" "org.kde.potd"
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc --group "Containments" --group "1" --group "Wallpaper" --group "org.kde.potd" --group "General" --key "FillMode" 2
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc --group "Containments" --group "1" --group "Wallpaper" --group "org.kde.potd" --group "General" --key "Provider" "bing"

# Konsole
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Appearance" --key "ColorScheme" "BreezeBlue"
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "Name" "Default"
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "Parent" "FALLBACK/"
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "SemanticInputClick" true
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "SemanticUpDown" true
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "StartInCurrentSessionDir" false
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "TerminalColumns" 120
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "General" --key "TerminalRows" 43
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Interaction Options" --key "AutoCopySelectedText" true
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Interaction Options" --key "MiddleClickPasteMode" 1
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Interaction Options" --key "TrimLeadingSpacesInSelectedText" true
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Interaction Options" --key "TrimTrailingSpacesInSelectedText" true
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Interaction Options" --key "TripleClickMode" 1
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Scrolling" --key "HistoryMode" 2
kwriteconfig6 --file ~/.local/share/konsole/Default.profile --group "Terminal Features" --key "UrlHintsModifiers" 67108864
kwriteconfig6 --file konsolerc --group "Desktop Entry" --key "DefaultProfile" "Default.profile"
kwriteconfig6 --file konsolerc --group "KonsoleWindow" --key "ShowWindowTitleOnTitleBar" true

qdbus-qt6 org.kde.GtkConfig /GtkConfig setGtkTheme Breeze
sleep 2
plasmashell --replace &
sleep 2

logger "Plasma desktop configuration complete"
