#!/bin/bash
set -oue pipefail

logger "Bash configuring for user"

if ! grep -q "# HorizonOS customizations" ~/.bashrc; then
    {
        echo ""
        echo "# HorizonOS customizations"
        echo "PROMPT_DIR_COLOR=\"1;96\""
        echo "bind 'set completion-ignore-case on'"
        echo "if command -v fzf >/dev/null 2>&1; then eval \"\$(fzf --bash)\"; fi"
    } | tee -a ~/.bashrc
fi

logger "Bash configuration complete"
