#!/bin/bash
set -oue pipefail

logger "HorizonOS installing flatpaks"

flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
flatpak override --user --filesystem=xdg-config/gtk-4.0:ro

FLATPAK_PACKAGES=(
    org.gtk.Gtk3theme.Breeze
    com.calibre_ebook.calibre
    com.github.PintaProject.Pinta
    com.github.tchx84.Flatseal
    com.moonlight_stream.Moonlight
    com.ranfdev.DistroShelf
    com.usebottles.bottles
    fr.handbrake.ghb
    hu.irl.cameractrls
    io.github.flattool.Warehouse
    io.github.plrigaux.sysd-manager
    io.github.slgobinath.SafeEyes
    io.github.zarestia_dev.rclone-manager
    io.qt.qdbusviewer
    net.cozic.joplin_desktop
    net.lutris.Lutris
    net.mediaarea.MediaInfo
    no.mifi.losslesscut
    org.audacityteam.Audacity
    org.avidemux.Avidemux
    org.bunkus.mkvtoolnix-gui
    org.chromium.Chromium
    org.deskflow.deskflow
    org.fkoehler.KTailctl
    org.gnome.meld
    org.gimp.GIMP
    org.inkscape.Inkscape
    org.libreoffice.LibreOffice
    org.mozilla.Thunderbird
    org.qbittorrent.qBittorrent
    page.codeberg.JakobDev.jdSystemMonitor
)

for package in "${FLATPAK_PACKAGES[@]}"; do
    if ! flatpak list --app --columns=application | grep -Fxq "$package"; then
        logger "Installing $package"
        flatpak install -y "$package" || true
    fi
done

flatpak override --user --env=WEBKIT_DISABLE_COMPOSITING_MODE=1 io.github.zarestia_dev.rclone-manager
flatpak override --user io.github.zarestia_dev.rclone-manager --talk-name=org.freedesktop.Flatpak
flatpak override --user io.github.zarestia_dev.rclone-manager --filesystem=~/.config/autostart:create

logger "HorizonOS flatpak installation completed"
