#!/bin/bash
set -ouex pipefail

logger -t horizon "Starting HorizonOS user setup"

if /usr/libexec/horizon-check-version $HOME/.horizon-version-actual; then
    exit 0
else
    EXIT_CODE=$?
fi

case $EXIT_CODE in
    1)
        /usr/libexec/horizon-post-install-user
        /usr/libexec/horizon-post-update-user
        ;;
    2)
        /usr/libexec/horizon-post-update-user
        ;;
    *)
        exit $EXIT_CODE
        ;;
esac

\cp -f /etc/horizon-version $HOME/.horizon-version-actual
exit 0
