#!/bin/bash
set -oue pipefail

logger "HorizonOS installing flatpaks"

flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
flatpak override --user --filesystem=xdg-config/gtk-4.0:ro

FLATPAK_PACKAGES=(
    org.gtk.Gtk3theme.Breeze
    com.calibre_ebook.calibre
    com.github.PintaProject.Pinta
    com.github.tchx84.Flatseal
    com.moonlight_stream.Moonlight
    com.ranfdev.DistroShelf
    com.usebottles.bottles
    fr.handbrake.ghb
    hu.irl.cameractrls
    io.github.flattool.Warehouse
    io.github.plrigaux.sysd-manager
    io.qt.qdbusviewer
    it.mijorus.gearlever
    net.hovancik.Stretchly
    net.lutris.Lutris
    net.mediaarea.MediaInfo
    no.mifi.losslesscut
    org.audacityteam.Audacity
    org.avidemux.Avidemux
    org.bunkus.mkvtoolnix-gui
    org.chromium.Chromium
    org.fkoehler.KTailctl
    org.gnome.meld
    org.gimp.GIMP
    org.inkscape.Inkscape
    org.kde.krdc
    org.libreoffice.LibreOffice
    org.qbittorrent.qBittorrent
)

for package in "${FLATPAK_PACKAGES[@]}"; do
    if ! flatpak list --app --columns=application | grep -Fxq "$package"; then
        logger "Installing $package"
        flatpak install -y "$package" || true
    fi
done

logger "HorizonOS flatpak installation completed"
