#!/bin/bash
set -oue pipefail

logger "Starting automatic system update"

if ! /usr/libexec/horizon-check-version /etc/horizon-version-actual; then
    logger "System update cancelled: first run post-install procedures"
    exit 0
fi

export LOG_FILE="/var/log/horizon-update.log"

BOOTC_UPDATED=$(/usr/libexec/horizon-update-bootc)

if [ "$BOOTC_UPDATED" = true ]; then
    /usr/libexec/horizon-notify "Update Completed" "Reboot to apply bootc updates."
fi

logger "System update: completed"
exit 0
