#!/bin/bash
set -ouex pipefail

logger -t horizon "Enabling Syncthing container service for user"

QUADLET_DIR="$HOME/.config/containers/systemd"
QUADLET_FILE="$QUADLET_DIR/syncthing.container"

if [ -f "$QUADLET_FILE" ]; then
	echo "Quadlet file $QUADLET_FILE already exists. Exiting."
	exit 0
fi

mkdir -p "$HOME/Sync"
mkdir -p "$QUADLET_DIR"

cat > "$QUADLET_FILE" <<'EOF'
[Unit]
Description=Syncthing
After=network-online.target
Wants=network-online.target

[Service]
ExecStartPre=-mkdir -p %h/.config/syncthing
ExecStartPre=-mkdir -p %h/Sync
Restart=on-failure
TimeoutStartSec=900

[Container]
ContainerName=syncthing
Image=lscr.io/linuxserver/syncthing:latest
AutoUpdate=registry

Environment=PUID=1000
Environment=PGID=1000
Environment=UMASK=022
Environment=TZ=Europe/Rome

Volume=%h/.config/syncthing:/config:Z
Volume=%h/Sync:/data/Sync:Z

PublishPort=8384:8384
PublishPort=22000:22000/tcp
PublishPort=22000:22000/udp
PublishPort=21027:21027/udp

Network=slirp4netns:allow_host_loopback=true
SecurityLabelDisable=true

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload

DESKTOP_FILE="$HOME/.local/share/applications/syncthing-webui.desktop"
mkdir -p "$HOME/.local/share/applications"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Syncthing Web UI
Comment=Open Syncthing Web Interface
Exec=xdg-open http://localhost:8384
Icon=applications-internet
Icon=folder-sync
Categories=Network;Utility;
Terminal=false
EOF
