#!/bin/bash
set -oue pipefail

logger "Configuring Bash aliases and enhancements for user"

lines=(
    "# HorizonOS aliases and shell enhancements"
    "bind 'set completion-ignore-case on'"
    "alias ls='lsd'"
    "alias du='dust'"
    "alias ps='procs'"
    "alias grep='rg'"
    "alias tldr='tldr --color'"
    "eval \"$(fzf --bash)\""
)

for line in "${lines[@]}"; do
    if ! grep -Fxq "$line" ~/.bashrc; then
        echo "$line" >> ~/.bashrc
    fi
done

if ! grep -q "atuin init bash" ~/.bashrc; then
  curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
  printf '
[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
' >> ~/.bashrc
  echo 'eval "$(atuin init bash --disable-ctrl-r)"' >> ~/.bashrc
fi
