#!/bin/bash
set -oue pipefail

logger "Enabling Syncthing container service for user"

QUADLET_DIR="$HOME/.config/containers/systemd"
QUADLET_FILE="$QUADLET_DIR/syncthing.container"

if [ -f "$QUADLET_FILE" ]; then
	echo "Quadlet file $QUADLET_FILE already exists. Exiting."
	exit 0
fi

mkdir -p "$HOME/Sync"
mkdir -p "$QUADLET_DIR"

PUID=$(id -u)
PGID=$(id -g)

cat > "$QUADLET_FILE" <<EOF
[Unit]
Description=Syncthing
After=network-online.target
Wants=network-online.target

[Service]
Restart=on-failure
TimeoutStartSec=900

[Container]
ContainerName=syncthing
Image=docker.io/syncthing/syncthing:latest
AutoUpdate=registry

Environment=PUID=1000
Environment=PGID=1000
Environment=UMASK=022
Environment=TZ=Europe/Rome

Volume=%h/Sync:/var/syncthing:Z

PublishPort=8384:8384
PublishPort=22000:22000/tcp
PublishPort=22000:22000/udp
PublishPort=21027:21027/udp

Network=slirp4netns:allow_host_loopback=true

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
