#!/bin/bash
set -ouex pipefail

/usr/libexec/horizon-check-version
EXIT_CODE=$?

case $EXIT_CODE in
    0)
        ;;
    1)
        /usr/libexec/horizon-post-install
        /usr/libexec/horizon-post-update
        ;;
    2)
        /usr/libexec/horizon-post-update
        ;;
    10)
        exit 10
        ;;
    *)
        exit 99
        ;;
esac

\cp -f /etc/horizon-version $HOME/.horizon-version
exit 0
