#!/bin/bash
set -ou pipefail

logger "System update: podman"

if ! command -v podman &> /dev/null; then
    logger "podman not found"
    exit 0
fi

images=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>" || true)
if [ -n "$images" ]; then
    for image in $images; do
        logger "podman updating $image"
        podman_output=$(podman pull "$image" 2>&1 || logger "podman error $image")
        if echo "$podman_output" | grep -q "Downloaded"; then
        fi
    done
    podman image prune -f 2>&1
    logger "podman images updated"
else
    logger "no podman images"
fi
exit 0