#!/bin/bash
set -oue pipefail

logger "HorizonOS system post install"

/usr/libexec/horizon-configure-fstab
/usr/libexec/horizon-configure-services
/usr/libexec/horizon-configure-sensors
/usr/libexec/horizon-configure-flatpak
/usr/libexec/horizon-configure-sddm

restorecon -Rv /var/lib/libvirt
restorecon -Rv /var/log/libvirt

logger "HorizonOS system post install complete"