#!/bin/bash
set -oue pipefail

FIREFOX_DIR="/usr/lib64/firefox"

echo "----------> Patching the Firefox wrapper for selectable profiles"
# Firefox's selectable profiles (about:profilemanager) break on ostree systems
# where /home is a symlink to /var/home: the primary profile runs with the
# profile path derived from $HOME (/home/<user>/...), while secondary profiles
# are launched with "--profile <path>", which Firefox passes through realpath()
# (/var/home/<user>/...). The SelectableProfileService compares the two as
# strings, never finds the current profile in its database, and about:editprofile
# stays blank with the profile menu missing. Giving Firefox a canonical HOME
# makes both sides agree. The Fedora wrapper is a shell script, so the export
# goes there: .desktop files cannot expand variables and would not cover
# launches from a terminal or xdg-open anyway.
FIREFOX_WRAPPER="/usr/bin/firefox"
ANCHOR="^# Run the browser$"

if ! grep -q "${ANCHOR}" "${FIREFOX_WRAPPER}"; then
    echo "ERROR: anchor '${ANCHOR}' not found in ${FIREFOX_WRAPPER}, wrapper layout changed" >&2
    exit 1
fi

sed -i "/${ANCHOR}/i\\
# HorizonOS: canonical HOME so selectable profiles resolve to the same path\\
# whether opened from profiles.ini or with --profile (see /home -> /var/home).\\
if [ -n \"\$HOME\" ] && [ -d \"\$HOME\" ]; then\\
    HOME=\$(realpath \"\$HOME\") && export HOME\\
fi\\
" "${FIREFOX_WRAPPER}"

echo "----------> Enabling the HorizonOS autoconfig"
# Makes Firefox run ${FIREFOX_DIR}/horizon.cfg at startup.
mkdir -p "${FIREFOX_DIR}/defaults/pref"
cat > "${FIREFOX_DIR}/defaults/pref/horizon-autoconfig.js" <<'EOF'
// HorizonOS: run /usr/lib64/firefox/horizon.cfg at startup (see that file).
pref("general.config.filename", "horizon.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);
EOF

# Sets the HorizonOS default preferences and registers the HorizonOS
# stylesheets for every profile of every user, so userChrome.css and
# toolkit.legacyUserProfileCustomizations.stylesheets are not needed. A user
# sheet registered here applies to all documents, web pages included, so each
# stylesheet scopes itself to chrome:// (and about:) documents.
cat > "${FIREFOX_DIR}/horizon.cfg" <<'EOF'
// HorizonOS autoconfig: the first line of this file is skipped by Firefox.

// Default preferences, still changeable by the user in about:config.
defaultPref("browser.tabs.loadBookmarksInTabs", true);
defaultPref("browser.tabs.closeWindowWithLastTab", false);
defaultPref("browser.search.openintab", true);

try {
    const sss = Components.classes["@mozilla.org/content/style-sheet-service;1"]
        .getService(Components.interfaces.nsIStyleSheetService);
    const io = Components.classes["@mozilla.org/network/io-service;1"]
        .getService(Components.interfaces.nsIIOService);

    for (const name of ["nova-less-rounded.css", "nova-system-accent.css"]) {
        const uri = io.newURI("file:///usr/lib64/firefox/horizon/" + name);
        if (!sss.sheetRegistered(uri, sss.USER_SHEET)) {
            sss.loadAndRegisterSheet(uri, sss.USER_SHEET);
        }
    }
} catch (e) {
    Components.utils.reportError(e);
}
EOF

echo "----------> Installing the Nova stylesheet"
# Firefox Nova with fewer rounded corners and no borders around the page.
# Based on "Better Nova": https://gist.github.com/suveshmoza/489d09e9c4d1e34f6a5f9f53a2bef23b
# The variable names come from Firefox's own CSS (tokens-shared.css in
# omni.ja); recheck them there if an update breaks something.
mkdir -p "${FIREFOX_DIR}/horizon"
cat > "${FIREFOX_DIR}/horizon/nova-less-rounded.css" <<'EOF'
/* HorizonOS: Firefox Nova with fewer rounded corners, generated by
   build_scripts/standard/firefox-config.sh and loaded by horizon.cfg. */
@-moz-document url-prefix("chrome://") {
    @media -moz-pref("browser.nova.enabled") {
        /* Page: no separator line above it and no rounded corners next to
           the sidebar */
        :root {
            --chrome-content-separator-color: unset !important;
        }

        .browserContainer {
            --content-area-start-radius: 0px !important;
        }

        .tab-background {
            border-radius: 8px !important;
        }

        /* Bookmarks: same radius as the tabs */
        #PersonalToolbar {
            --toolbarbutton-border-radius: 8px !important;
        }

        /* Bookmarks in compact density: standard toolbar height, with the
           items vertically centered */
        :root[uidensity="compact"] #PersonalToolbar {
            min-height: 32px !important;
            max-height: 32px !important;
        }

        :root[uidensity="compact"] #PersonalToolbar toolbarbutton,
        :root[uidensity="compact"] #PersonalToolbar .bookmark-item {
            padding-top: 4px !important;
            padding-bottom: 4px !important;
        }

        /* Menus and panels */
        :root, menupopup, panel {
            --popup-border-radius: 8px !important;
            --panel-border-radius: 8px !important;
            --panel-menuitem-border-radius: 4px !important;
            --menuitem-border-radius: 4px !important;
        }
    }
}
EOF

echo "----------> Installing the Nova system accent stylesheet"
# Replaces Nova's violet with the system accent color (KDE accent, through the
# GTK colors Plasma exports). Nova keeps a violet palette in tokens-shared.css
# (--color-violet-* and --color-violet-desaturated-*) that drives the accent,
# the button tints and its slightly violet grays: each step is rebuilt from
# AccentColor with the original OKLCH lightness and the chroma scaled from
# violet-50, so contrast stays as Nova designed it. about: pages use the same
# tokens, so they are included too.
cat > "${FIREFOX_DIR}/horizon/nova-system-accent.css" <<'EOF'
/* HorizonOS: Firefox Nova with the system accent color instead of violet,
   generated by build_scripts/standard/firefox-config.sh and loaded by horizon.cfg.
   A gray system accent gives a neutral palette. */
@-moz-document url-prefix("chrome://"), url-prefix("about:") {
    @media -moz-pref("browser.nova.enabled") {
        :root {
            --color-violet-0: oklch(from AccentColor 95.6% calc(c * 0.13) h) !important;
            --color-violet-10: oklch(from AccentColor 91.8% calc(c * 0.23) h) !important;
            --color-violet-20: oklch(from AccentColor 84.8% calc(c * 0.42) h) !important;
            --color-violet-30: oklch(from AccentColor 75.6% calc(c * 0.68) h) !important;
            --color-violet-40: oklch(from AccentColor 65.5% calc(c * 0.98) h) !important;
            --color-violet-50: oklch(from AccentColor 54.7% calc(c * 1.00) h) !important;
            --color-violet-60: oklch(from AccentColor 44.6% calc(c * 0.82) h) !important;
            --color-violet-70: oklch(from AccentColor 35.2% calc(c * 0.61) h) !important;
            --color-violet-80: oklch(from AccentColor 26.6% calc(c * 0.38) h) !important;
            --color-violet-90: oklch(from AccentColor 20.1% calc(c * 0.14) h) !important;
            --color-violet-100: oklch(from AccentColor 27% calc(c * 0.48) h) !important;
            --color-violet-110: oklch(from AccentColor 20% calc(c * 0.24) h) !important;
            --color-violet-desaturated-0: oklch(from AccentColor 95.9% calc(c * 0.05) h) !important;
            --color-violet-desaturated-10: oklch(from AccentColor 92.1% calc(c * 0.15) h) !important;
            --color-violet-desaturated-20: oklch(from AccentColor 85.2% calc(c * 0.25) h) !important;
            --color-violet-desaturated-30: oklch(from AccentColor 76.4% calc(c * 0.33) h) !important;
            --color-violet-desaturated-40: oklch(from AccentColor 65.8% calc(c * 0.41) h) !important;
            --color-violet-desaturated-50: oklch(from AccentColor 54.8% calc(c * 0.43) h) !important;
            --color-violet-desaturated-60: oklch(from AccentColor 44.6% calc(c * 0.40) h) !important;
            --color-violet-desaturated-70: oklch(from AccentColor 35.0% calc(c * 0.38) h) !important;
            --color-violet-desaturated-80: oklch(from AccentColor 26.6% calc(c * 0.34) h) !important;
            --color-violet-desaturated-90: oklch(from AccentColor 20.0% calc(c * 0.31) h) !important;
        }

        /* Toolbar button hover: hardcoded violet in tokens-platform.css, same
           values as violet-desaturated-50/30 at 25% and 40%. Not applied with
           a color theme (lwtheme) so it keeps its own colors. */
        :root:is([theme-in-app], :not([lwtheme])) {
            --toolbarbutton-background-color-hover: light-dark(
                color-mix(in srgb, var(--color-violet-desaturated-50) 25%, transparent),
                color-mix(in srgb, var(--color-violet-desaturated-30) 25%, transparent)) !important;
            --toolbarbutton-background-color-active: light-dark(
                color-mix(in srgb, var(--color-violet-desaturated-50) 40%, transparent),
                color-mix(in srgb, var(--color-violet-desaturated-30) 40%, transparent)) !important;
        }
    }
}
EOF
