#!/bin/bash
set -oue pipefail

FIREFOX_DIR="/usr/lib64/firefox"

echo "----------> Patching the Firefox wrapper for selectable profiles"
# Firefox's selectable profiles (about:profilemanager) break on ostree systems
# where /home is a symlink to /var/home: the primary profile runs with the
# profile path derived from $HOME (/home/<user>/...), while secondary profiles
# are launched with "--profile <path>", which Firefox passes through realpath()
# (/var/home/<user>/...). The SelectableProfileService compares the two as
# strings, never finds the current profile in its database, and about:editprofile
# stays blank with the profile menu missing. Giving Firefox a canonical HOME
# makes both sides agree. The Fedora wrapper is a shell script, so the export
# goes there: .desktop files cannot expand variables and would not cover
# launches from a terminal or xdg-open anyway.
FIREFOX_WRAPPER="/usr/bin/firefox"
ANCHOR="^# Run the browser$"

if ! grep -q "${ANCHOR}" "${FIREFOX_WRAPPER}"; then
    echo "ERROR: anchor '${ANCHOR}' not found in ${FIREFOX_WRAPPER}, wrapper layout changed" >&2
    exit 1
fi

sed -i "/${ANCHOR}/i\\
# HorizonOS: canonical HOME so selectable profiles resolve to the same path\\
# whether opened from profiles.ini or with --profile (see /home -> /var/home).\\
if [ -n \"\$HOME\" ] && [ -d \"\$HOME\" ]; then\\
    HOME=\$(realpath \"\$HOME\") && export HOME\\
fi\\
" "${FIREFOX_WRAPPER}"

echo "----------> Enabling the HorizonOS autoconfig"
# Makes Firefox run ${FIREFOX_DIR}/horizon.cfg at startup.
mkdir -p "${FIREFOX_DIR}/defaults/pref"
cat > "${FIREFOX_DIR}/defaults/pref/horizon-autoconfig.js" <<'EOF'
// HorizonOS: run /usr/lib64/firefox/horizon.cfg at startup (see that file).
pref("general.config.filename", "horizon.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);
EOF

# Registers the HorizonOS stylesheets for every profile of every user, so
# userChrome.css and toolkit.legacyUserProfileCustomizations.stylesheets are
# not needed. A user sheet registered here applies to all documents, web pages
# included, so each stylesheet scopes itself to chrome:// documents.
cat > "${FIREFOX_DIR}/horizon.cfg" <<'EOF'
// HorizonOS autoconfig: the first line of this file is skipped by Firefox.
try {
    const sss = Components.classes["@mozilla.org/content/style-sheet-service;1"]
        .getService(Components.interfaces.nsIStyleSheetService);
    const io = Components.classes["@mozilla.org/network/io-service;1"]
        .getService(Components.interfaces.nsIIOService);

    for (const name of ["nova-less-rounded.css"]) {
        const uri = io.newURI("file:///usr/lib64/firefox/horizon/" + name);
        if (!sss.sheetRegistered(uri, sss.USER_SHEET)) {
            sss.loadAndRegisterSheet(uri, sss.USER_SHEET);
        }
    }
} catch (e) {
    Components.utils.reportError(e);
}
EOF

echo "----------> Installing the Nova stylesheet"
# Firefox Nova with fewer rounded corners and no borders around the page.
# Based on "Better Nova": https://gist.github.com/suveshmoza/489d09e9c4d1e34f6a5f9f53a2bef23b
# The variable names come from Firefox's own CSS (tokens-shared.css in
# omni.ja); recheck them there if an update breaks something.
mkdir -p "${FIREFOX_DIR}/horizon"
cat > "${FIREFOX_DIR}/horizon/nova-less-rounded.css" <<'EOF'
/* HorizonOS: Firefox Nova with fewer rounded corners, generated by
   build_scripts/standard/firefox.sh and loaded by horizon.cfg. */
@-moz-document url-prefix("chrome://") {
    @media -moz-pref("browser.nova.enabled") {
        /* Page: no separator line above it and no rounded corners next to
           the sidebar */
        :root {
            --chrome-content-separator-color: unset !important;
        }

        .browserContainer {
            --content-area-start-radius: 0px !important;
        }

        .tab-background {
            border-radius: 8px !important;
        }

        /* Bookmarks: same radius as the tabs */
        #PersonalToolbar {
            --toolbarbutton-border-radius: 8px !important;
        }

        /* Menus and panels */
        :root, menupopup, panel {
            --popup-border-radius: 8px !important;
            --panel-border-radius: 8px !important;
            --panel-menuitem-border-radius: 4px !important;
            --menuitem-border-radius: 4px !important;
        }
    }
}
EOF
